name: Kubernetes Certifications unit tests

on: [push, pull_request]

#- name: Cache
#  uses: actions/cache@v2.1.3
#  with:
#    # A list of files, directories, and wildcard patterns to cache and restore
#    path: 
#    # An explicit key for restoring and saving the cache
#    key: 
#    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
#    restore-keys: # optional
#    # The chunk size used to split up large files during upload, in bytes
#    upload-chunk-size: # optional
jobs:
  Unit-testing:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install flake8 pytest
        pip install -r kubernetes/requirements.txt.lock
    - name: Run unit tests
      run: |
        cd kubernetes
        python -m unittest tests/tests.py
        #- name: Lint with flake8
        #  run: |
        #    # stop the build if there are Python syntax errors or undefined names
        #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        #- name: Test with pytest
        #  run: |
        #    pytest
