---
name: Lint Code Base
on: [push]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint with GitHub Super Linter
        uses: github/super-linter@v3
        env:
          PYTHON_FLAKE8_CONFIG_FILE: ${RUNNER_WORKSPACE}/.flake8 # Otherwise it is searched next to workflow definitions
          VALIDATE_PYTHON_FLAKE8: true  # Code lint
          VALIDATE_PYTHON_BLACK: true   # Code style
          VALIDATE_YAML: true           # CI
          VALIDATE_MARKDOWN: true       # READMEs and stuff
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
